version: '3'

services:

  # app:
  #   image: node:18.13-slim
  #   user: node
  #   command: sh -c "npm start"
  #   ports:
  #     - 3000:3000
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=dbtest
      - MONGO_NON_ROOT_USERNAME=dbtest
      - MONGO_NON_ROOT_PASSWORD=password

    volumes:
      - ./database-data:/data/db
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

    restart: unless-stopped
    depends_on:
      - mongodb

volumes:
  database-data: